"""Modern Facts Shorts generator built on MoneyPrinterTurbo's own CLI.

Pipeline for one YouTube Short:

1. ``ensure_config`` writes ``config.toml`` (fresh CI checkout) and points the
   existing LLM layer at Gemini using ``GEMINI_API_KEY`` from the environment.
2. A topic is either supplied (``--topic`` / ``SHORTS_TOPIC``) or generated by
   Gemini through the repository's existing LLM adapter.
3. Abstract 9:16 background clips are generated locally with FFmpeg
   (``scripts/generate_shorts_backgrounds``), so no stock-footage API key is
   needed. They are fed to the stock pipeline through ``--video-source local``.
4. ``cli.py`` runs the unchanged MoneyPrinterTurbo pipeline: Gemini script →
   Edge TTS voiceover (free, no key) → Edge subtitles → local materials →
   vertical 9:16 MP4 with burned-in captions.
5. The finished MP4, SRT, script, and metadata are copied to an output
   directory for the GitHub Actions artifact upload.
6. When the ``UPLOAD_POST_API_KEY`` and ``UPLOAD_POST_USERNAME`` environment
   variables are present, the *existing* ``app/services/upload_post.py``
   cross-post service publishes the finished video to YouTube (private by
   default) through Upload-Post, whose dashboard is where the YouTube
   OAuth 2.0 consent happens. The upload runs only after video generation
   succeeds, its outcome is written to ``upload-status.json``, and an upload
   failure never changes the generation exit code or the artifact.

Usage:
    export GEMINI_API_KEY=...
    uv run python scripts/run_modern_facts_shorts.py
    uv run python scripts/run_modern_facts_shorts.py --topic "..." --script "..."
    uv run python scripts/run_modern_facts_shorts.py --verify-upload-status storage/modern_facts/upload-status.json
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import time
from pathlib import Path
from typing import Callable, Sequence

REPO_ROOT = Path(__file__).resolve().parents[1]

DEFAULT_VOICE_NAME = "en-US-AndrewMultilingualNeural-Male"
DEFAULT_VOICE_RATE = 1.1
DEFAULT_LANGUAGE = "en-US"
DEFAULT_OUTPUT_DIR = REPO_ROOT / "storage" / "modern_facts"
DEFAULT_BACKGROUNDS_DIR = REPO_ROOT / "storage" / "local_videos" / "modern-facts"
DEFAULT_LLM_PROVIDER = "gemini"
DEFAULT_TASK_TIMEOUT = 3000
DEFAULT_CROSS_POST_TIMEOUT = 3600.0
DEFAULT_YOUTUBE_PRIVACY = "private"
DEFAULT_UPLOAD_PLATFORMS = "youtube"
UPLOAD_STATUS_FILENAME = "upload-status.json"
YOUTUBE_PRIVACY_VALUES = ("private", "unlisted", "public")
UPLOAD_PLATFORM_VALUES = ("youtube", "tiktok", "instagram")
UPLOAD_SECRET_ENV_VARS = ("UPLOAD_POST_API_KEY", "UPLOAD_POST_USERNAME")

TOPIC_PROMPT = """\
You pick video topics for the YouTube Shorts channel "Modern Facts", which
publishes fast-paced shorts about artificial intelligence, future technology,
robotics, space, and emerging science.

Rules:
- Reply with exactly ONE topic and nothing else.
- The topic must be a specific, surprising, believable claim or fact, not a
  generic category.
- Maximum 14 words. No quotes, no emoji, no colon-prefixed labels.
- Written as a title-style hook that makes viewers want to watch.
"""

DEFAULT_SCRIPT_PROMPT = """\
Write the narration for a YouTube Short for the channel "Modern Facts".
- Total length: 90 to 110 words, readable in about 40 seconds.
- First sentence must be a strong hook that works as the on-screen title.
- Punchy, factual, forward-looking tone about AI or future technology.
- One idea per sentence. No headings, no stage directions, no emojis.
- End with a single short question or bold statement. Do not ask for likes.
"""


def ensure_config(
    config_path: Path,
    example_path: Path,
    *,
    llm_provider: str = "",
    gemini_api_key: str = "",
    model_name: str = "",
    upload_api_key: str = "",
    upload_username: str = "",
    upload_platforms: Sequence[str] = (),
    upload_privacy: str = "",
    upload_enabled: bool | None = None,
) -> list[str]:
    """Create/patch ``config.toml`` so the stock services do the right thing.

    LLM fields come from the Gemini environment variables; publishing fields
    come from the Upload-Post environment variables. Only these Modern Facts
    fields are touched: the rest of the configuration stays exactly as
    shipped. Secrets are never echoed into the returned change labels, and
    they are written only to ``config.toml`` (gitignored).

    ``upload_enabled=None`` leaves an existing Upload-Post configuration
    untouched (so a locally configured account still works without env vars);
    ``False`` force-disables publishing (``--no-upload``).
    """
    changes: list[str] = []
    if not config_path.is_file():
        if not example_path.is_file():
            raise FileNotFoundError(
                f"cannot create {config_path}: {example_path} is missing"
            )
        shutil.copyfile(example_path, config_path)
        changes.append(f"created {config_path.name} from {example_path.name}")

    import toml

    data = toml.load(str(config_path))
    app_section = data.setdefault("app", {})

    def apply(key: str, value: str, label: str) -> None:
        if value and app_section.get(key) != value:
            app_section[key] = value
            changes.append(label)

    def apply_value(key: str, value: object, label: str) -> None:
        if app_section.get(key) != value:
            app_section[key] = value
            changes.append(label)

    apply("llm_provider", llm_provider, f"app.llm_provider = {llm_provider}")
    apply("gemini_api_key", gemini_api_key, "app.gemini_api_key set from GEMINI_API_KEY")
    apply("gemini_model_name", model_name, f"app.gemini_model_name = {model_name}")

    if upload_enabled is True:
        apply(
            "upload_post_api_key",
            upload_api_key,
            "app.upload_post_api_key set from UPLOAD_POST_API_KEY",
        )
        apply(
            "upload_post_username",
            upload_username,
            "app.upload_post_username set from UPLOAD_POST_USERNAME",
        )
        platforms = [str(platform) for platform in upload_platforms]
        if platforms:
            apply_value(
                "upload_post_platforms",
                platforms,
                "app.upload_post_platforms = " + ", ".join(platforms),
            )
        if upload_privacy:
            apply_value(
                "upload_post_youtube_privacy_status",
                upload_privacy,
                f"app.upload_post_youtube_privacy_status = {upload_privacy}",
            )
        apply_value(
            "upload_post_enabled", True, "app.upload_post_enabled = true"
        )
        apply_value(
            "upload_post_auto_upload", True, "app.upload_post_auto_upload = true"
        )
    elif upload_enabled is False:
        apply_value(
            "upload_post_enabled", False, "app.upload_post_enabled = false"
        )
        apply_value(
            "upload_post_auto_upload", False, "app.upload_post_auto_upload = false"
        )

    if changes:
        config_path.write_text(toml.dumps(data), encoding="utf-8")
    return changes


def read_upload_settings(config_path: Path) -> dict:
    """Mirror the pipeline's own publishing gate for reporting decisions.

    ``task.py`` only schedules a cross-post when ``is_configured()`` (enabled
    + API key + username) AND ``auto_upload`` are both true and platforms are
    non-empty; this reads the same ``config.toml`` fields so the report says
    "disabled" exactly when the pipeline skipped publishing.
    """
    app_section: dict = {}
    try:
        import toml

        app_section = toml.load(str(config_path)).get("app", {})
    except Exception:
        app_section = {}
    platforms = app_section.get("upload_post_platforms", ["tiktok", "instagram"])
    if not isinstance(platforms, list):
        platforms = []
    configured = bool(
        app_section.get("upload_post_enabled")
        and app_section.get("upload_post_auto_upload")
        and app_section.get("upload_post_api_key")
        and app_section.get("upload_post_username")
        and platforms
    )
    return {
        "configured": configured,
        "platforms": [str(platform) for platform in platforms],
        "privacy": str(
            app_section.get("upload_post_youtube_privacy_status")
            or "public"
        ),
    }


def build_upload_report(
    task_result: dict,
    *,
    task_id: str,
    upload_settings: dict,
    stop_at: str = "video",
) -> dict:
    """Turn the CLI cross-post outcome into a stable upload-status payload.

    The report never contains credentials; it is written next to the video
    and consumed by ``--verify-upload-status``.
    """
    state = task_result.get("cross_post_state")
    if stop_at != "video":
        status = "skipped"
        reason = f"video pipeline stopped at '{stop_at}'"
    elif not upload_settings.get("configured"):
        status = "disabled"
        reason = (
            "Upload-Post publishing is not configured; set "
            + " and ".join(UPLOAD_SECRET_ENV_VARS)
            + " (see docs/modern-facts-shorts.md)"
        )
    elif state == "complete":
        status = "uploaded"
        reason = None
    elif state == "failed":
        status = "failed"
        reason = str(
            task_result.get("cross_post_error") or "unknown upload error"
        )
    elif state in ("pending", "processing"):
        status = "failed"
        reason = (
            "cross-post upload did not finish before the CLI exited; "
            "outcome unconfirmed"
        )
    else:
        status = "failed"
        reason = "cross-post was not scheduled despite being configured"
    return {
        "status": status,
        "reason": reason,
        "cross_post_state": state,
        "task_id": task_id,
        "platforms": list(upload_settings.get("platforms") or []),
        "youtube_privacy_status": upload_settings.get("privacy", "public"),
        "results": task_result.get("cross_post_results") or [],
        "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
    }


def write_upload_status(output_dir: Path, report: dict) -> Path:
    output_dir.mkdir(parents=True, exist_ok=True)
    path = output_dir / UPLOAD_STATUS_FILENAME
    path.write_text(
        json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    return path


def append_step_summary(report: dict) -> None:
    """Append a credential-free publish summary when running in GitHub Actions."""
    target = os.getenv("GITHUB_STEP_SUMMARY")
    if not target:
        return

    def one_line(value: object) -> str:
        return re.sub(r"\s+", " ", str(value)).strip()

    lines = [
        "## YouTube upload",
        "",
        f"- status: `{one_line(report.get('status'))}`",
        f"- privacy: `{one_line(report.get('youtube_privacy_status'))}`",
        "- platforms: `"
        + one_line(", ".join(report.get("platforms") or []))
        + "`",
    ]
    if report.get("reason"):
        lines.append(f"- detail: {one_line(report['reason'])}")
    try:
        with open(target, "a", encoding="utf-8") as handle:
            handle.write("\n".join(lines) + "\n")
    except OSError:
        pass


def verify_upload_status(status_path: Path) -> int:
    """Exit non-zero only when a configured publish actually failed.

    A missing file means generation never succeeded (the job already failed
    earlier), and ``disabled``/``skipped`` mean publishing was never
    requested — neither is an upload error.
    """
    if not status_path.is_file():
        print(
            f"no upload status file at {status_path}; video generation did "
            "not complete, skipping the YouTube upload check"
        )
        return 0
    try:
        data = json.loads(status_path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        print(f"could not read upload status {status_path}: {exc}", file=sys.stderr)
        return 1
    status = str(data.get("status") or "failed")
    reason = str(data.get("reason") or "")
    if status in {"uploaded", "disabled", "skipped"}:
        detail = f" - {reason}" if reason else ""
        print(f"YouTube upload status: {status}{detail}")
        return 0
    message = f"YouTube upload failed: {reason or 'unknown error'}"
    print(message, file=sys.stderr)
    if os.getenv("GITHUB_ACTIONS") == "true":
        print(f"::error::{message}")
    return 1


def build_topic_prompt(channel: str = "Modern Facts") -> str:
    return TOPIC_PROMPT.replace("Modern Facts", channel)


def parse_topic_response(raw: object) -> str:
    """Reduce an LLM reply to a single usable topic line ('' when unusable)."""
    if not isinstance(raw, str):
        return ""
    text = raw.strip()
    if not text or text.startswith("Error:"):
        return ""
    if text.startswith("```"):
        text = re.sub(r"^```[a-zA-Z0-9]*\s*", "", text)
        text = re.sub(r"\s*```$", "", text)
    for line in text.splitlines():
        candidate = line.strip().lstrip("#").lstrip("-*").strip()
        candidate = re.sub(r'^(topic|title)\s*:\s*', "", candidate, flags=re.I)
        candidate = candidate.strip(" \t\"'\u201c\u201d")
        if candidate:
            return candidate[:160]
    return ""


def pick_topic(
    prompt: str,
    *,
    generate: Callable[..., str] | None = None,
    attempts: int = 3,
) -> str:
    """Ask the configured LLM for one topic, retrying transient failures."""
    if generate is None:
        if str(REPO_ROOT) not in sys.path:
            sys.path.insert(0, str(REPO_ROOT))
        from app.services import llm as llm_service

        generate = llm_service._generate_response

    last_reply: object = None
    for _ in range(attempts):
        last_reply = generate(prompt=prompt)
        topic = parse_topic_response(last_reply)
        if topic:
            return topic
    raise RuntimeError(
        "failed to generate a topic with the configured LLM; "
        f"last reply: {str(last_reply)[:300]}"
    )


def build_cli_command(
    *,
    python: str,
    cli_path: Path,
    subject: str = "",
    script: str = "",
    materials: Sequence[Path] = (),
    voice_name: str = DEFAULT_VOICE_NAME,
    voice_rate: float = DEFAULT_VOICE_RATE,
    language: str = DEFAULT_LANGUAGE,
    paragraph_number: int = 2,
    script_prompt: str = "",
    aspect: str = "9:16",
    stop_at: str = "video",
    video_count: int = 1,
    cross_post_timeout: float | None = None,
    extra_args: Sequence[str] = (),
) -> list[str]:
    """Build the argument vector for the existing ``cli.py`` entry point."""
    command = [python, str(cli_path)]
    if subject:
        command.extend(["--video-subject", subject])
    if script:
        command.extend(["--video-script", script])
    command.extend(
        [
            "--video-source",
            "local",
            "--video-materials",
            ",".join(str(path) for path in materials),
            "--video-aspect",
            aspect,
            "--video-language",
            language,
            "--paragraph-number",
            str(paragraph_number),
            "--voice-name",
            voice_name,
            "--voice-rate",
            f"{voice_rate:g}",
            "--subtitle-enabled",
            "--video-count",
            str(video_count),
            "--stop-at",
            stop_at,
        ]
    )
    if script_prompt:
        command.extend(["--video-script-prompt", script_prompt])
    if cross_post_timeout is not None:
        command.extend(["--cross-post-timeout", f"{cross_post_timeout:g}"])
    command.extend(extra_args)
    return command


def run_cli_task(
    command: Sequence[str],
    *,
    timeout: int = DEFAULT_TASK_TIMEOUT,
    require_video: bool = True,
) -> dict:
    """Run ``cli.py`` and return its single-line JSON result."""
    completed = subprocess.run(
        list(command),
        cwd=str(REPO_ROOT),
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        timeout=timeout,
        check=False,
    )
    stdout = completed.stdout or ""
    result = None
    for line in reversed(stdout.splitlines()):
        stripped = line.strip()
        if stripped.startswith("{"):
            try:
                result = json.loads(stripped)
                break
            except json.JSONDecodeError:
                continue
    if completed.returncode != 0 or result is None:
        stderr_tail = "\n".join((completed.stderr or "").splitlines()[-40:])
        raise RuntimeError(
            "cli.py failed with exit code "
            f"{completed.returncode}; last log lines:\n{stderr_tail}"
        )
    payload = result.get("result") if isinstance(result.get("result"), dict) else {}
    if not payload or payload.get("state") not in (None, "completed"):
        error = (payload or {}).get("error") or "unknown task error"
        raise RuntimeError(f"video task did not complete: {error}")
    task_id = str(result.get("task_id") or "")
    videos = [str(path) for path in (payload.get("videos") or [])]
    if not task_id:
        raise RuntimeError("cli.py finished without a task id")
    if require_video and not videos:
        raise RuntimeError("cli.py finished without an output video")
    result["task_id"] = task_id
    result["videos"] = videos
    return result


def derive_subject(script: str, limit: int = 100) -> str:
    """Use the script's opening sentence as the video subject/topic."""
    first = re.split(r"[.!?\n]", script.strip(), maxsplit=1)[0].strip()
    first = re.sub(r"\s+", " ", first)
    return first[:limit].strip() or "Modern Facts short"


def slugify(text: str, max_length: int = 40) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    return slug[:max_length].rstrip("-") or "short"


def collect_outputs(
    *,
    task_id: str,
    videos: Sequence[str],
    output_dir: Path,
    subject: str,
    script_text: str,
    voice_name: str,
    extra_meta: dict | None = None,
) -> dict:
    """Copy the finished artifacts into ``output_dir`` and write metadata."""
    if str(REPO_ROOT) not in sys.path:
        sys.path.insert(0, str(REPO_ROOT))
    from app.utils import utils

    task_dir = Path(utils.task_dir(task_id))
    output_dir.mkdir(parents=True, exist_ok=True)
    stamp = time.strftime("%Y%m%d-%H%M%S")
    slug = slugify(subject)

    copied_videos = []
    for index, source in enumerate(videos, start=1):
        source_path = Path(source)
        if not source_path.is_file():
            continue
        suffix = "" if len(videos) == 1 else f"-{index}"
        target = output_dir / f"modern-facts-{stamp}-{slug}{suffix}.mp4"
        shutil.copy2(source_path, target)
        copied_videos.append(str(target))

    copied: dict[str, list[str]] = {"videos": copied_videos}
    for name in ("subtitle.srt", "script.json"):
        source_path = task_dir / name
        if source_path.is_file():
            target = output_dir / f"{stamp}-{slug}-{name}"
            shutil.copy2(source_path, target)
            copied.setdefault(name, []).append(str(target))

    meta = {
        "subject": subject,
        "script": script_text,
        "voice_name": voice_name,
        "task_id": task_id,
        "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "outputs": copied,
    }
    if extra_meta:
        meta.update(extra_meta)
    meta_path = output_dir / f"{stamp}-{slug}-meta.json"
    meta_path.write_text(json.dumps(meta, ensure_ascii=False, indent=2), encoding="utf-8")
    copied["meta"] = [str(meta_path)]
    return meta


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Generate one Modern Facts YouTube Short end to end: Gemini topic "
            "and script, free Edge TTS voiceover, local FFmpeg backgrounds, "
            "burned-in captions, 9:16 output, and (when the Upload-Post "
            "secrets are configured) a private YouTube upload through the "
            "existing app/services/upload_post.py cross-post service."
        )
    )
    parser.add_argument(
        "--topic",
        default="",
        help="video topic; generated with Gemini when omitted "
        "(env fallback: SHORTS_TOPIC)",
    )
    parser.add_argument(
        "--script",
        default="",
        help="complete narration; skips Gemini script generation when provided "
        "(env fallback: SHORTS_SCRIPT)",
    )
    parser.add_argument(
        "--llm-provider",
        default=os.getenv("SHORTS_LLM_PROVIDER") or DEFAULT_LLM_PROVIDER,
        help=f"LLM provider written to config.toml (default: {DEFAULT_LLM_PROVIDER})",
    )
    parser.add_argument(
        "--gemini-model",
        default=os.getenv("SHORTS_GEMINI_MODEL") or "",
        help="optional Gemini model override; empty uses the provider default",
    )
    parser.add_argument(
        "--voice-name",
        default=os.getenv("SHORTS_VOICE_NAME") or DEFAULT_VOICE_NAME,
        help=f"Edge TTS voice (default: {DEFAULT_VOICE_NAME})",
    )
    parser.add_argument(
        "--voice-rate",
        type=float,
        default=float(os.getenv("SHORTS_VOICE_RATE") or DEFAULT_VOICE_RATE),
        help=f"speech rate (default: {DEFAULT_VOICE_RATE})",
    )
    parser.add_argument("--language", default=DEFAULT_LANGUAGE)
    parser.add_argument(
        "--paragraph-number",
        type=int,
        default=2,
        help="script paragraphs requested from the LLM (default: 2)",
    )
    parser.add_argument(
        "--script-prompt",
        default=DEFAULT_SCRIPT_PROMPT,
        help="additional LLM requirements for script generation",
    )
    parser.add_argument(
        "--materials",
        default="",
        help="comma-separated existing local material files; skips background "
        "generation when provided",
    )
    parser.add_argument(
        "--backgrounds-dir",
        default=str(DEFAULT_BACKGROUNDS_DIR),
        help="directory for generated background clips",
    )
    parser.add_argument(
        "--background-count",
        type=int,
        default=8,
        help="number of background clips to generate (default: 8)",
    )
    parser.add_argument(
        "--background-duration",
        type=float,
        default=12.0,
        help="duration of each background clip in seconds (default: 12)",
    )
    parser.add_argument(
        "--force-backgrounds",
        action="store_true",
        help="regenerate background clips even if they already exist",
    )
    parser.add_argument(
        "--output-dir",
        default=str(DEFAULT_OUTPUT_DIR),
        help="directory that receives the finished artifacts",
    )
    parser.add_argument(
        "--stop-at",
        default="video",
        choices=["script", "audio", "subtitle", "materials", "video"],
        help="pipeline stage to stop after (default: video; "
        "'terms' is unavailable with local materials)",
    )
    parser.add_argument(
        "--task-timeout",
        type=int,
        default=DEFAULT_TASK_TIMEOUT,
        help=f"seconds to wait for cli.py (default: {DEFAULT_TASK_TIMEOUT})",
    )
    parser.add_argument(
        "--no-upload",
        action="store_true",
        help="skip YouTube publishing even when Upload-Post secrets are configured",
    )
    parser.add_argument(
        "--youtube-privacy",
        choices=list(YOUTUBE_PRIVACY_VALUES),
        default=os.getenv("SHORTS_YOUTUBE_PRIVACY") or DEFAULT_YOUTUBE_PRIVACY,
        help=(
            "YouTube visibility for published videos "
            f"(default: {DEFAULT_YOUTUBE_PRIVACY}; env: SHORTS_YOUTUBE_PRIVACY)"
        ),
    )
    parser.add_argument(
        "--upload-platforms",
        default=os.getenv("SHORTS_UPLOAD_PLATFORMS") or DEFAULT_UPLOAD_PLATFORMS,
        help=(
            "comma-separated Upload-Post platforms to publish to "
            f"(default: {DEFAULT_UPLOAD_PLATFORMS}; env: SHORTS_UPLOAD_PLATFORMS)"
        ),
    )
    parser.add_argument(
        "--cross-post-timeout",
        type=float,
        default=DEFAULT_CROSS_POST_TIMEOUT,
        help=(
            "seconds cli.py waits for the publish step before reporting "
            f"(default: {int(DEFAULT_CROSS_POST_TIMEOUT)})"
        ),
    )
    parser.add_argument(
        "--verify-upload-status",
        default="",
        metavar="PATH",
        help=(
            "check an upload-status.json file and exit non-zero when the "
            "upload failed; skips video generation"
        ),
    )
    parser.add_argument(
        "--cli-arg",
        action="append",
        default=[],
        help="extra raw argument forwarded to cli.py; repeatable",
    )
    return parser.parse_args(argv)


def resolve_materials(args: argparse.Namespace, log) -> list[Path]:
    explicit = [part.strip() for part in (args.materials or "").split(",") if part.strip()]
    if explicit:
        paths = [Path(item).expanduser().resolve() for item in explicit]
        missing = [str(path) for path in paths if not path.is_file()]
        if missing:
            raise FileNotFoundError(f"material file(s) not found: {', '.join(missing)}")
        log(f"using {len(paths)} provided local material(s)")
        return paths

    if args.stop_at not in {"materials", "video"}:
        return []
    if str(REPO_ROOT) not in sys.path:
        sys.path.insert(0, str(REPO_ROOT))
    from scripts.generate_shorts_backgrounds import generate_backgrounds

    log(
        f"generating {args.background_count} local background clip(s) "
        f"in {args.backgrounds_dir}"
    )
    return generate_backgrounds(
        Path(args.backgrounds_dir),
        count=args.background_count,
        duration=args.background_duration,
        force=args.force_backgrounds,
        log=log,
    )


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv)
    if str(REPO_ROOT) not in sys.path:
        sys.path.insert(0, str(REPO_ROOT))

    def log(message: str) -> None:
        print(message, file=sys.stderr, flush=True)

    if args.verify_upload_status:
        return verify_upload_status(Path(args.verify_upload_status))

    if args.cross_post_timeout <= 0:
        log("error: --cross-post-timeout must be greater than 0")
        return 2

    upload_platforms = [
        platform.strip().lower()
        for platform in (args.upload_platforms or "").split(",")
        if platform.strip()
    ]
    invalid_platforms = [
        platform for platform in upload_platforms if platform not in UPLOAD_PLATFORM_VALUES
    ]
    if not upload_platforms or invalid_platforms:
        log(
            "error: --upload-platforms must be a comma-separated list of "
            + ", ".join(UPLOAD_PLATFORM_VALUES)
        )
        return 2

    topic = (args.topic or os.getenv("SHORTS_TOPIC", "")).strip()
    script = (args.script or os.getenv("SHORTS_SCRIPT", "")).strip()
    gemini_api_key = os.getenv("GEMINI_API_KEY", "").strip()
    upload_api_key = os.getenv("UPLOAD_POST_API_KEY", "").strip()
    upload_username = os.getenv("UPLOAD_POST_USERNAME", "").strip()

    # Publishing is opt-in through the Upload-Post environment secrets. With
    # secrets present the pipeline publishes automatically; --no-upload
    # force-disables it; without secrets an already configured local
    # config.toml keeps working untouched.
    if args.no_upload:
        upload_enabled: bool | None = False
    elif upload_api_key and upload_username:
        upload_enabled = True
    else:
        upload_enabled = None

    upload_config_kwargs: dict = {}
    if upload_enabled is True:
        upload_config_kwargs = {
            "upload_api_key": upload_api_key,
            "upload_username": upload_username,
            "upload_platforms": upload_platforms,
            "upload_privacy": args.youtube_privacy,
            "upload_enabled": True,
        }
    elif upload_enabled is False:
        upload_config_kwargs = {"upload_enabled": False}

    try:
        changes = ensure_config(
            REPO_ROOT / "config.toml",
            REPO_ROOT / "config.example.toml",
            llm_provider=args.llm_provider,
            gemini_api_key=gemini_api_key,
            model_name=args.gemini_model,
            **upload_config_kwargs,
        )
    except (OSError, ValueError) as exc:
        log(f"error: could not prepare config.toml: {exc}")
        return 2
    for change in changes:
        log(f"config: {change}")

    upload_settings = read_upload_settings(REPO_ROOT / "config.toml")
    if upload_settings["configured"] and args.stop_at == "video":
        log(
            "publishing enabled: "
            + ", ".join(upload_settings["platforms"])
            + f" (privacy: {upload_settings['privacy']})"
        )
    elif args.stop_at == "video":
        reason = (
            "--no-upload given"
            if args.no_upload
            else " / ".join(UPLOAD_SECRET_ENV_VARS) + " not configured"
        )
        log(f"publishing disabled: {reason}")

    needs_llm = not script
    if needs_llm and not gemini_api_key:
        has_stored_key = False
        try:
            import toml

            stored = toml.load(str(REPO_ROOT / "config.toml"))
            has_stored_key = bool(stored.get("app", {}).get("gemini_api_key"))
        except Exception:
            has_stored_key = False
        if not has_stored_key:
            log(
                "error: GEMINI_API_KEY is not set and config.toml has no "
                "gemini_api_key; add the GitHub Actions secret GEMINI_API_KEY "
                "or pass --script to skip the LLM"
            )
            return 2

    try:
        if not topic:
            if script:
                topic = derive_subject(script)
                log(f"subject: {topic} (derived from --script)")
            else:
                log("requesting a topic from the configured LLM...")
                topic = pick_topic(build_topic_prompt())
                log(f"topic: {topic}")
        if not script:
            log("generating the narration script with the configured LLM...")
    except RuntimeError as exc:
        log(f"error: {exc}")
        return 1

    try:
        materials = resolve_materials(args, log)
    except (RuntimeError, ValueError, OSError, FileNotFoundError) as exc:
        log(f"error: {exc}")
        return 1

    if args.stop_at in {"materials", "video"} and not materials:
        log("error: no local materials are available for the materials stage")
        return 1

    command = build_cli_command(
        python=sys.executable,
        cli_path=REPO_ROOT / "cli.py",
        subject=topic,
        script=script,
        materials=materials,
        voice_name=args.voice_name,
        voice_rate=args.voice_rate,
        language=args.language,
        paragraph_number=args.paragraph_number,
        script_prompt="" if script else args.script_prompt,
        stop_at=args.stop_at,
        cross_post_timeout=args.cross_post_timeout,
        extra_args=args.cli_arg,
    )
    log("running: " + " ".join(_redact(command)))

    # The publish step runs inside cli.py after the video is final; its wait
    # time sits on top of generation, so widen the subprocess deadline only
    # when publishing is actually active.
    subprocess_timeout = args.task_timeout
    if upload_settings["configured"] and args.stop_at == "video":
        subprocess_timeout += int(args.cross_post_timeout) + 300

    try:
        result = run_cli_task(
            command,
            timeout=subprocess_timeout,
            require_video=args.stop_at == "video",
        )
    except (RuntimeError, subprocess.TimeoutExpired) as exc:
        log(f"error: {exc}")
        return 1

    script_text = script
    if not script_text:
        try:
            from app.utils import utils

            task_script = Path(utils.task_dir(result["task_id"])) / "script.json"
            payload = json.loads(task_script.read_text(encoding="utf-8"))
            script_text = str(payload.get("script") or "")
        except Exception:
            script_text = ""

    try:
        meta = collect_outputs(
            task_id=result["task_id"],
            videos=result["videos"],
            output_dir=Path(args.output_dir),
            subject=topic,
            script_text=script_text,
            voice_name=args.voice_name,
            extra_meta={
                "llm_provider": args.llm_provider,
                "aspect": "9:16",
                "language": args.language,
                "materials": [str(path) for path in materials],
            },
        )
    except OSError as exc:
        log(f"error: could not collect outputs: {exc}")
        return 1

    # The artifacts are already collected at this point: a failed publish is
    # reported below and never fails generation or removes the video.
    task_payload = result.get("result") if isinstance(result.get("result"), dict) else {}
    upload_report = build_upload_report(
        task_payload,
        task_id=result["task_id"],
        upload_settings=upload_settings,
        stop_at=args.stop_at,
    )
    try:
        status_path = write_upload_status(Path(args.output_dir), upload_report)
    except OSError as exc:
        log(f"error: could not write upload status: {exc}")
        return 1
    append_step_summary(upload_report)
    upload_detail = f" - {upload_report['reason']}" if upload_report.get("reason") else ""
    log(f"YouTube upload: {upload_report['status']}{upload_detail}")

    print(
        json.dumps(
            {
                "topic": topic,
                "task_id": result["task_id"],
                "outputs": meta["outputs"],
                "upload": upload_report,
                "upload_status_file": str(status_path),
            },
            ensure_ascii=False,
        )
    )
    return 0


def _redact(command: Sequence[str]) -> list[str]:
    """Keep the visible command line free of any configured secrets."""
    secret_markers = ("gemini_api_key", "upload_post_api_key", "upload_post_username")
    return [
        "<redacted>" if any(marker in token for marker in secret_markers) else token
        for token in command
    ]


if __name__ == "__main__":
    raise SystemExit(main())
